import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

export default defineSchema({
  sites: defineTable({
    publicId: v.string(),
    name: v.string(),
    type: v.union(v.literal('blog'), v.literal('forum'), v.literal('showcase')),
    status: v.string(),
    locale: v.string(),
    timezone: v.string(),
    publicUrl: v.string(),
    settingsVersion: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('byPublicId', ['publicId']),
  users: defineTable({
    publicId: v.string(),
    emailNormalized: v.string(),
    displayName: v.string(),
    avatarAssetId: v.optional(v.string()),
    status: v.string(),
    role: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('byPublicId', ['publicId']).index('byEmail', ['emailNormalized']),
  posts: defineTable({
    publicId: v.string(),
    title: v.string(),
    slug: v.string(),
    excerpt: v.string(),
    bodyMarkdown: v.string(),
    status: v.string(),
    authorId: v.string(),
    featuredAssetId: v.optional(v.string()),
    tagIds: v.array(v.string()),
    publishedAt: v.optional(v.number()),
    scheduledFor: v.optional(v.number()),
    revision: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
    deletedAt: v.optional(v.number()),
  }).index('byPublicId', ['publicId']).index('bySlug', ['slug']).index('byStatus', ['status']).index('byAuthorId', ['authorId']),
  postRevisions: defineTable({
    publicId: v.string(),
    postId: v.string(),
    revision: v.number(),
    title: v.string(),
    slug: v.string(),
    excerpt: v.string(),
    bodyMarkdown: v.string(),
    editorId: v.string(),
    createdAt: v.number(),
  }).index('byPost', ['postId']).index('byPostRevision', ['postId', 'revision']),
  tags: defineTable({
    publicId: v.string(),
    name: v.string(),
    slug: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('byPublicId', ['publicId']).index('bySlug', ['slug']),
  forumCategories: defineTable({
    publicId: v.string(),
    name: v.string(),
    slug: v.string(),
    description: v.string(),
    sortOrder: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('byPublicId', ['publicId']).index('bySlug', ['slug']),
  threads: defineTable({
    publicId: v.string(),
    categoryId: v.string(),
    authorId: v.string(),
    title: v.string(),
    status: v.string(),
    pinned: v.boolean(),
    locked: v.boolean(),
    postCount: v.number(),
    lastPostAt: v.number(),
    lastPostPublicId: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('byPublicId', ['publicId']).index('byLastPostAt', ['lastPostAt']),
  forumPosts: defineTable({
    publicId: v.string(),
    threadId: v.string(),
    parentPostId: v.optional(v.string()),
    authorId: v.string(),
    bodyMarkdown: v.string(),
    revision: v.number(),
    editedAt: v.optional(v.number()),
    createdAt: v.number(),
    deletedAt: v.optional(v.number()),
    moderationState: v.string(),
  }).index('byPublicId', ['publicId']).index('byThread', ['threadId']),
  readStates: defineTable({
    publicId: v.string(),
    userId: v.string(),
    threadId: v.string(),
    lastReadAt: v.number(),
    updatedAt: v.number(),
  }).index('byUserThread', ['userId', 'threadId']),
  reports: defineTable({
    publicId: v.string(),
    reporterId: v.string(),
    targetType: v.string(),
    targetId: v.string(),
    reason: v.string(),
    status: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    resolvedBy: v.optional(v.string()),
  }).index('byPublicId', ['publicId']).index('byStatus', ['status']),
  reactions: defineTable({
    publicId: v.string(),
    userId: v.string(),
    targetType: v.string(),
    targetId: v.string(),
    kind: v.string(),
    createdAt: v.number(),
  }).index('byTarget', ['targetType', 'targetId']),
  moderationActions: defineTable({
    publicId: v.string(),
    moderatorId: v.string(),
    action: v.string(),
    targetType: v.string(),
    targetId: v.string(),
    reason: v.string(),
    createdAt: v.number(),
  }).index('byPublicId', ['publicId']),
  projects: defineTable({
    publicId: v.string(),
    projectType: v.optional(v.string()),
    title: v.string(),
    slug: v.string(),
    summary: v.string(),
    bodyMarkdown: v.string(),
    status: v.string(),
    authorId: v.string(),
    assetIds: v.array(v.string()),
    tagIds: v.array(v.string()),
    customFields: v.any(),
    sortOrder: v.number(),
    publishedAt: v.optional(v.number()),
    revision: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('byPublicId', ['publicId']).index('bySlug', ['slug']).index('byStatus', ['status']).index('byAuthorId', ['authorId']),
  inquiries: defineTable({
    publicId: v.string(),
    projectId: v.optional(v.string()),
    name: v.string(),
    email: v.string(),
    message: v.string(),
    status: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('byPublicId', ['publicId']).index('byStatus', ['status']),
  notifications: defineTable({
    publicId: v.string(),
    userId: v.string(),
    kind: v.string(),
    targetType: v.string(),
    targetId: v.string(),
    body: v.string(),
    readAt: v.optional(v.number()),
    createdAt: v.number(),
  }).index('byUser', ['userId']),
  auditEvents: defineTable({
    publicId: v.string(),
    actorId: v.string(),
    action: v.string(),
    targetType: v.string(),
    targetId: v.string(),
    requestId: v.string(),
    metadata: v.any(),
    createdAt: v.number(),
  }).index('byPublicId', ['publicId']).index('byActorId', ['actorId']),
  idempotencyKeys: defineTable({
    publicId: v.string(),
    actorId: v.string(),
    clientMutationId: v.string(),
    result: v.any(),
    createdAt: v.number(),
    expiresAt: v.number(),
  }).index('byKey', ['actorId', 'clientMutationId']),
  migrationRecords: defineTable({
    publicId: v.string(),
    version: v.number(),
    appliedAt: v.number(),
  }).index('byVersion', ['version']),
  mediaUploads: defineTable({
    publicId: v.string(),
    userId: v.string(),
    mediaType: v.string(),
    byteSize: v.number(),
    status: v.string(),
    createdAt: v.number(),
    expiresAt: v.number(),
  }).index('byPublicId', ['publicId']).index('byUser', ['userId']),
  assets: defineTable({
    publicId: v.string(),
    digest: v.string(),
    mediaType: v.string(),
    byteSize: v.number(),
    width: v.optional(v.number()),
    height: v.optional(v.number()),
    storageId: v.optional(v.string()),
    originalMediaType: v.string(),
    originalByteSize: v.number(),
    originalDigest: v.string(),
    compressed: v.boolean(),
    status: v.string(),
    createdBy: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('byPublicId', ['publicId']).index('byDigest', ['digest']),
});
