'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRealtimeState } from './realtime';
import type { ActionName, Post, Project, PublicState, Thread } from '@/lib/types';

export default function Admin() {
  const { state, connection, act, refresh } = useRealtimeState();
  const [tab, setTab] = useState('overview');
  const [modal, setModal] = useState<'post' | 'project' | 'thread' | 'user' | null>(null);
  const [selected, setSelected] = useState<Post | Project | null>(null);
  const [error, setError] = useState('');
  const [flash, setFlash] = useState('');

  useEffect(() => { if (state && !state.setupComplete) window.location.href = '/setup'; }, [state]);
  if (!state) return <div className="admin-shell"><div className="empty">Loading administration…</div></div>;
  if (!state.setupComplete) return null;
  if (!state.currentUser) return <Login onDone={() => void refresh()} />;

  const run = async (action: ActionName, payload: Record<string, unknown> = {}) => {
    setError(''); setFlash('');
    try { const result = await act(action, payload); setFlash('Saved successfully'); return result; } catch (caught) { setError(caught instanceof Error ? caught.message : 'Action failed'); return null; }
  };
  const user = state.currentUser;
  const unread = state.notifications.filter((notification) => !notification.readAt).length;
  const nav = [
    ['overview', 'Overview'], ['content', state.site.type === 'forum' ? 'Forum' : state.site.type === 'showcase' ? 'Showcase' : 'Posts'], ...(state.site.type === 'showcase' ? [['inquiries', 'Inquiries']] : []), ['users', 'Users'], ['settings', 'Settings'],
  ] as [string, string][];

  return <div className="shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">P</span><span>{state.site.name}<small>Administration</small></span></Link><div className="top-actions"><span className="live-dot">{connection}</span><Link className="button secondary" href="/">View site</Link><button className="button ghost" onClick={() => void act('auth.signOut')}>Sign out</button></div></header><main className="admin-shell"><div className="admin-head"><div><p className="eyebrow">Operator workspace</p><h1>Good morning, {user.displayName.split(' ')[0]}.</h1></div><div className="row"><span className="badge">{user.role}</span><button className="button" onClick={() => setModal(state.site.type === 'forum' ? 'thread' : state.site.type === 'showcase' ? 'project' : 'post')}>Create {state.site.type === 'forum' ? 'thread' : state.site.type === 'showcase' ? 'project' : 'post'}</button></div></div><nav className="admin-nav">{nav.map(([key, label]) => <button className={tab === key ? 'active' : ''} key={key} onClick={() => setTab(key)}>{label}{key === 'notifications' && unread ? ` · ${unread}` : ''}</button>)}</nav>{error && <div className="notice error" style={{ marginBottom: 16 }}>{error}</div>}{flash && <div className="notice" style={{ marginBottom: 16 }}>{flash}</div>}{tab === 'overview' && <Overview state={state} onTab={setTab} />}{tab === 'content' && state.site.type === 'blog' && <Posts state={state} onEdit={(post) => { setSelected(post); setModal('post'); }} onRun={run} />}{tab === 'content' && state.site.type === 'forum' && <Threads state={state} onEdit={() => setModal(null)} onRun={run} />}{tab === 'content' && state.site.type === 'showcase' && <Projects state={state} onEdit={(project) => { setSelected(project); setModal('project'); }} onRun={run} />}{tab === 'inquiries' && <Inquiries state={state} onRun={run} />}{tab === 'users' && <Users state={state} onRun={run} onCreate={() => setModal('user')} />}{tab === 'settings' && <Settings state={state} onRun={run} />}</main>{modal === 'post' && <PostEditor post={selected as Post | null} onClose={() => { setModal(null); setSelected(null); }} onSave={async (payload) => { const result = await run('posts.save', payload); if (result) { setModal(null); setSelected(null); } }} />}{modal === 'project' && <ProjectEditor project={selected as Project | null} onClose={() => { setModal(null); setSelected(null); }} onSave={async (payload) => { const result = await run('projects.save', payload); if (result) { setModal(null); setSelected(null); } }} />}{modal === 'thread' && <ThreadEditor onClose={() => setModal(null)} onSave={async (payload) => { const result = await run('threads.create', payload); if (result) setModal(null); }} />}{modal === 'user' && <UserEditor onClose={() => setModal(null)} onSave={async (payload) => { const result = await run('users.create', payload); if (result) setModal(null); }} />}</div>;
}

function Overview({ state, onTab }: { state: PublicState; onTab: (tab: string) => void }) {
  const published = state.site.type === 'blog' ? state.posts.length : state.site.type === 'forum' ? state.threads.length : state.projects.length;
  return <div className="grid"><div className="card panel"><p className="eyebrow">Published</p><div style={{ fontSize: 44, fontWeight: 800, letterSpacing: '-.08em' }}>{published}</div><p>{state.site.type} content records visible publicly.</p><button className="link-button" style={{ marginTop: 18 }} onClick={() => onTab('content')}>Manage content →</button></div><div className="card panel"><p className="eyebrow">Audience</p><div style={{ fontSize: 44, fontWeight: 800, letterSpacing: '-.08em' }}>{state.users.length}</div><p>Known accounts in this installation.</p><button className="link-button" style={{ marginTop: 18 }} onClick={() => onTab('users')}>Manage users →</button></div><div className="card panel"><p className="eyebrow">Realtime</p><div style={{ fontSize: 44, fontWeight: 800, letterSpacing: '-.08em' }}>0.5s</div><p>Target delivery after commit on the reference runtime.</p><div className="notice" style={{ marginTop: 18 }}>Reactive queries are healthy</div></div><div className="card panel" style={{ gridColumn: '1 / -1' }}><div className="row between"><div><h3>Recent activity</h3><p>Privileged operations are retained in the audit stream.</p></div><span className="badge">Append-only</span></div><div className="table-wrap" style={{ marginTop: 20 }}><table><thead><tr><th>Operation</th><th>Target</th><th>When</th></tr></thead><tbody>{state.audit.slice(-8).reverse().map((event) => <tr key={event.publicId}><td><strong>{event.action}</strong></td><td className="muted">{event.targetType} · {event.targetId.slice(0, 8)}</td><td className="muted">{new Date(event.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div></div></div>;
}

function Posts({ state, onEdit, onRun }: { state: PublicState; onEdit: (post: Post) => void; onRun: (action: ActionName, payload?: Record<string, unknown>) => Promise<unknown> }) {
  return <div className="card panel"><div className="row between" style={{ marginBottom: 18 }}><div><h3>Published posts</h3><p>Drafts and published entries use optimistic revisions.</p></div><span className="badge">{state.posts.length} live</span></div>{state.posts.length === 0 ? <div className="empty">No posts yet.</div> : <div className="table-wrap"><table><thead><tr><th>Entry</th><th>Status</th><th>Published</th><th /></tr></thead><tbody>{state.posts.map((post) => <tr key={post.publicId}><td><strong>{post.title}</strong><div className="tiny muted">/{post.slug} · r{post.revision}</div></td><td><span className="badge">{post.status}</span></td><td className="muted">{post.publishedAt ? new Date(post.publishedAt).toLocaleDateString() : '—'}</td><td><div className="row" style={{ justifyContent: 'flex-end' }}><button className="button ghost" onClick={() => onEdit(post)}>Edit</button>{post.status === 'published' ? <button className="button secondary" onClick={() => void onRun('posts.unpublish', { publicId: post.publicId })}>Unpublish</button> : <button className="button" onClick={() => void onRun('posts.publish', { publicId: post.publicId })}>Publish</button>}</div></td></tr>)}</tbody></table></div>}</div>;
}

function Threads({ state, onEdit, onRun }: { state: PublicState; onEdit: (thread: Thread) => void; onRun: (action: ActionName, payload?: Record<string, unknown>) => Promise<unknown> }) {
  return <div className="card panel"><div className="row between" style={{ marginBottom: 18 }}><div><h3>Forum threads</h3><p>Locking and moderation changes are reactive.</p></div><span className="badge">{state.threads.length} total</span></div>{state.threads.length === 0 ? <div className="empty">No threads yet.</div> : <div className="table-wrap"><table><thead><tr><th>Thread</th><th>Activity</th><th>State</th><th /></tr></thead><tbody>{state.threads.map((thread) => <tr key={thread.publicId}><td><strong>{thread.title}</strong><div className="tiny muted">{thread.postCount} posts</div></td><td className="muted">{new Date(thread.lastPostAt).toLocaleString()}</td><td><span className="badge">{thread.locked ? 'Locked' : 'Open'}</span></td><td><div className="row" style={{ justifyContent: 'flex-end' }}><button className="button ghost" onClick={() => onEdit(thread)}>Moderate</button><button className="button secondary" onClick={() => void onRun(thread.locked ? 'threads.unlock' : 'threads.lock', { publicId: thread.publicId })}>{thread.locked ? 'Unlock' : 'Lock'}</button></div></td></tr>)}</tbody></table></div>}</div>;
}

function Projects({ state, onEdit, onRun }: { state: PublicState; onEdit: (project: Project) => void; onRun: (action: ActionName, payload?: Record<string, unknown>) => Promise<unknown> }) {
  return <div className="card panel"><div className="row between" style={{ marginBottom: 18 }}><div><h3>Showcase projects</h3><p>Published projects update connected visitors without refresh.</p></div><span className="badge">{state.projects.length} live</span></div>{state.projects.length === 0 ? <div className="empty">No projects yet.</div> : <div className="table-wrap"><table><thead><tr><th>Project</th><th>Status</th><th>Updated</th><th /></tr></thead><tbody>{state.projects.map((project) => <tr key={project.publicId}><td><strong>{project.title}</strong><div className="tiny muted">/{project.slug} · r{project.revision}</div></td><td><span className="badge">{project.status}</span></td><td className="muted">{new Date(project.updatedAt).toLocaleDateString()}</td><td><div className="row" style={{ justifyContent: 'flex-end' }}><button className="button ghost" onClick={() => onEdit(project)}>Edit</button><button className="button" onClick={() => void onRun('projects.publish', { publicId: project.publicId })}>Publish</button></div></td></tr>)}</tbody></table></div>}</div>;
}

function Inquiries({ state, onRun }: { state: PublicState; onRun: (action: ActionName, payload?: Record<string, unknown>) => Promise<unknown> }) {
  return <div className="card panel"><div className="row between" style={{ marginBottom: 18 }}><div><h3>Inquiry inbox</h3><p>New inquiries create realtime admin notifications.</p></div><span className="badge">{state.inquiries.filter((inquiry) => inquiry.status === 'new').length} new</span></div>{state.inquiries.length === 0 ? <div className="empty">No inquiries yet.</div> : <div className="stack">{state.inquiries.map((inquiry) => <div className="card panel" key={inquiry.publicId}><div className="row between"><div><strong>{inquiry.name}</strong><div className="tiny muted">{inquiry.email} · {new Date(inquiry.createdAt).toLocaleString()}</div></div><span className="badge">{inquiry.status}</span></div><p style={{ marginTop: 14 }}>{inquiry.message}</p><select className="input" value={inquiry.status} onChange={(event) => void onRun('inquiries.updateStatus', { publicId: inquiry.publicId, status: event.target.value })}><option value="new">New</option><option value="read">Read</option><option value="replied">Replied</option><option value="closed">Closed</option></select></div>)}</div>}</div>;
}

function Users({ state, onRun, onCreate }: { state: PublicState; onRun: (action: ActionName, payload?: Record<string, unknown>) => Promise<unknown>; onCreate: () => void }) {
  return <div className="card panel"><div className="row between" style={{ marginBottom: 18 }}><div><h3>Users and roles</h3><p>Owner, administrators, editors, moderators, authors, and members.</p></div><button className="button" onClick={onCreate}>Add user</button></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th /></tr></thead><tbody>{state.users.map((account) => <tr key={account.publicId}><td><strong>{account.displayName}</strong><div className="tiny muted">{account.emailNormalized}</div></td><td><select className="input" value={account.role} disabled={account.role === 'owner'} onChange={(event) => void onRun('users.setRoles', { publicId: account.publicId, role: event.target.value })}>{['owner', 'administrator', 'editor', 'moderator', 'author', 'member'].map((role) => <option key={role} value={role}>{role}</option>)}</select></td><td><span className="badge">{account.status}</span></td><td className="muted tiny">{new Date(account.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></div>;
}

function Settings({ state, onRun }: { state: PublicState; onRun: (action: ActionName, payload?: Record<string, unknown>) => Promise<unknown> }) {
  const [form, setForm] = useState({ name: state.site.name, publicUrl: state.site.publicUrl, locale: state.site.locale, timezone: state.site.timezone });
  return <div className="stack"><div className="card panel"><h3>Site settings</h3><p>Changes are versioned and recorded in the audit stream.</p><form className="form" style={{ marginTop: 22 }} onSubmit={(event) => { event.preventDefault(); void onRun('settings.update', form); }}><div className="form-grid"><label>Site name<input className="input" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Public URL<input className="input" value={form.publicUrl} onChange={(event) => setForm({ ...form, publicUrl: event.target.value })} /></label><label>Locale<input className="input" value={form.locale} onChange={(event) => setForm({ ...form, locale: event.target.value })} /></label><label>Timezone<input className="input" value={form.timezone} onChange={(event) => setForm({ ...form, timezone: event.target.value })} /></label></div><button className="button" type="submit">Save settings</button></form></div><PackTools /></div>;
}

function PackTools() {
  const [message, setMessage] = useState('');
  const importPack = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    setMessage('Verifying and restoring pack…');
    const response = await fetch('/api/pack', { method: 'POST', headers: { 'content-type': 'application/octet-stream' }, body: file });
    if (!response.ok) { const body = await response.json().catch(() => ({ error: 'Restore failed' })); setMessage(body.error ?? 'Restore failed'); return; }
    window.location.reload();
  };
  return <div className="card panel"><div className="row between"><div><h3>Portable backup</h3><p>Export a public content pack or restore one into this installation.</p></div><span className="badge">Version 1</span></div>{message && <div className="notice" style={{ marginTop: 16 }}>{message}</div>}<div className="row" style={{ marginTop: 20 }}><a className="button" href="/api/pack">Export public pack</a><label className="button secondary" style={{ cursor: 'pointer' }}>Restore pack<input type="file" accept=".pcpack,application/zip" hidden onChange={(event) => void importPack(event)} /></label></div><p className="tiny muted" style={{ marginTop: 14 }}>Public packs exclude passwords, sessions, signing keys, and environment secrets.</p></div>;
}

function PostEditor({ post, onClose, onSave }: { post: Post | null; onClose: () => void; onSave: (payload: Record<string, unknown>) => Promise<void> }) { return <Editor title={post ? 'Edit post' : 'New post'} fields={post ? { title: post.title, slug: post.slug, excerpt: post.excerpt, bodyMarkdown: post.bodyMarkdown } : { title: '', slug: '', excerpt: '', bodyMarkdown: '' }} onClose={onClose} onSave={(payload) => onSave({ ...payload, publicId: post?.publicId, expectedRevision: post?.revision ?? 0, status: 'draft' })} />; }
function ProjectEditor({ project, onClose, onSave }: { project: Project | null; onClose: () => void; onSave: (payload: Record<string, unknown>) => Promise<void> }) { return <Editor title={project ? 'Edit project' : 'New project'} fields={project ? { title: project.title, slug: project.slug, excerpt: project.summary, bodyMarkdown: project.bodyMarkdown } : { title: '', slug: '', excerpt: '', bodyMarkdown: '' }} onClose={onClose} onSave={(payload) => onSave({ ...payload, publicId: project?.publicId, expectedRevision: project?.revision ?? 0, status: 'draft', summary: payload.excerpt })} />; }
function ThreadEditor({ onClose, onSave }: { onClose: () => void; onSave: (payload: Record<string, unknown>) => Promise<void> }) { return <Editor title="Start a thread" fields={{ title: '', excerpt: '', bodyMarkdown: '' }} onClose={onClose} onSave={(payload) => onSave({ title: payload.title, bodyMarkdown: payload.bodyMarkdown, categoryId: 'general' })} />; }
function UserEditor({ onClose, onSave }: { onClose: () => void; onSave: (payload: Record<string, unknown>) => Promise<void> }) { return <Editor title="Add user" fields={{ title: '', excerpt: '', bodyMarkdown: '' }} onClose={onClose} onSave={(payload) => onSave({ displayName: payload.title, email: payload.excerpt, password: payload.bodyMarkdown, role: 'member' })} />; }

function Editor({ title, fields, onClose, onSave }: { title: string; fields: Record<string, string>; onClose: () => void; onSave: (payload: Record<string, unknown>) => Promise<void> }) {
  const [form, setForm] = useState(fields); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { await onSave(form); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Save failed'); } finally { setBusy(false); } };
  const field = (name: string, label: string, multiline = false) => <label>{label}{multiline ? <textarea className="input" value={form[name] ?? ''} onChange={(event) => setForm({ ...form, [name]: event.target.value })} /> : <input className="input" value={form[name] ?? ''} onChange={(event) => setForm({ ...form, [name]: event.target.value })} />}</label>;
  return <div className="modal-backdrop" onClick={onClose}><form className="modal" onClick={(event) => event.stopPropagation()} onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">Content editor</p><h2>{title}</h2></div><button type="button" className="button ghost" onClick={onClose}>Cancel</button></div><div className="form">{error && <div className="notice error">{error}</div>}{field('title', title === 'Add user' ? 'Display name' : 'Title')}{field('excerpt', title === 'Add user' ? 'Email' : 'Summary')}{field('bodyMarkdown', title === 'Add user' ? 'Temporary password' : 'Body in Markdown', true)}<button className="button" type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save draft'}</button></div></form></div>;
}

function Login({ onDone }: { onDone: () => void }) {
  const { act } = useRealtimeState(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  return <div className="setup"><div className="brand"><span className="brand-mark">P</span><span>Portable Core<small>Secure administration</small></span></div><form className="card setup-card form" onSubmit={(event) => { event.preventDefault(); void act('auth.signIn', { email, password }).then(onDone).catch((caught) => setError(caught instanceof Error ? caught.message : 'Sign in failed')); }}><div><p className="eyebrow">Administration</p><h1>Sign in.</h1><p className="hero-copy">Manage content and portable site data.</p></div>{error && <div className="notice error">{error}</div>}<label>Email<input className="input" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input className="input" type="password" required value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="button" type="submit">Sign in</button><Link href="/setup" className="tiny muted">First-run setup</Link></form></div>;
}
